version: 2
updates:
- package-ecosystem: gomod
  directory: /greeter_server
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /.circleci/
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
