version: 2.1
orbs:
  aqua: aquaproj/aqua@0.2.1
jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aqua/install-aqua:
          version: v1.20.2
      - run:
          command: aqua i
      - run:
          command: |
            cd greeter_server
            aqua exec go build main.go
      - run:
          command: |
            greeter_server/main
          background: true
      - run:
          command: |
            aqua exec grpcurl -plaintext localhost:50051 list
workflows:
  build:
    jobs:
      - test
