version: 2.1
jobs:
  test:
    docker:
      - image: golang:1.21.4
    steps:
      - checkout
      - run:
          command: |
            curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v3.0.1/aqua-installer | bash -s -- -v v2.37.2
            echo 'export PATH="$HOME/.local/share/aquaproj-aqua/bin:$PATH"' >> "$BASH_ENV"
      - run:
          command: aqua install --only-link
      - run:
          command: |
            go build main.go
      - run:
          command: |
            ./main
          background: true
      - run:
          command: |
            grpcurl -plaintext localhost:50051 list
workflows:
  build:
    jobs:
      - test
