version: 2.1
jobs:
  test:
    docker:
      - image: golang:1.19.2
    steps:
      - checkout
      - run:
          command: |
            curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash -s -- -v v1.21.0
      - run:
          command: aqua install --only-link
      - run:
          command: |
            cd greeter_server
            go build main.go
      - run:
          command: |
            greeter_server/main
          background: true
      - run:
          command: |
            grpcurl -plaintext localhost:50051 list
workflows:
  build:
    jobs:
      - test
