version: 2.1
orbs:
  aqua: aquaproj/aqua@0.2.1
jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aqua/install-aqua:
          version: v1.20.2
      - run:
          command: |
            echo 'export PATH=~/.local/share/aquaproj-aqua/bin:"$PATH"' >> "$BASH_ENV"
      - run:
          command: |
            cd greeter_server
            go run main.go
          background: true
      - run:
          command: |
            grpcurl -plaintext localhost:50051 list
workflows:
  build:
    jobs:
      - test
