version: 2.1
orbs:
  aqua: aquaproj/aqua@0.2.1
jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aqua/install-aqua:
          version: v1.20.2
      - aqua/aqua-install:
          aqua_root_dir: ~/.local/share/aquaproj-aqua
      - run:
          command: |
            which go
            which grpcurl
            echo $PATH
      - run:
          command: |
            cd greeter_server
            go run main.go
          background: true
      - run:
          command: |
            grpcurl -plaintext localhost:50051 list
workflows:
  build:
    jobs:
      - test
